version: '2.1'

services:
  palette.local:
    container_name: 'palette.local'
    build:
      context: ./build/
      dockerfile: dockerfile

    ports:
      - '80:80'
      - '443:443'
      - '9001:9001' # Supervisor
      - '8025:8025' # Mailhog

    volumes:
      - ./../:/var/www/html
